name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        -
    - name: Pipenv for Github Actions
      uses: VaultVulp/action-pipenv@v1.0.0

    - name: Test with pytest
      run: pytest
